ShoppingCart tests
DZarudnyi/SpringBootBookShop pull request #17
Opened 2024-02-15 14:59 UTC by DZarudnyi

2024-02-15 19:26 UTC, DZarudnyi commented
![image](https://github.com/DZarudnyi/SpringBootBookShop/assets/77063748/9c742ae0-9004-4592-94c7-ce7709ee84f6)

2024-02-16 09:23 UTC, olekskov requested changes

2024-02-16 09:23 UTC, olekskov commented on src/main/java/com/example/books/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
Taking into account that you have only two roles I don't see necessity to put both of them into annotation.
If all roles can access endpoint you can just remove annotation as you security config requires tyo be authenticated anyway
```suggestion
```
Please recheck all similar cases

2024-02-16 09:23 UTC, olekskov commented on src/main/java/com/example/books/dto/cartitem/CartItemDto.java
> +public class CartItemDto {
I don't like approach where part of DTOs are records and part are simple classes.
This is inconsistent approach and each time you use new dto class you should check how to work with it.
Please make all of DTOs either records or classes

2024-02-16 09:23 UTC, olekskov commented on src/test/resources/database/books/insert-controller-testing-book.sql
> +VALUES(123, 'Title1', 'Author1', '978-0-545-01022-1', 20.00, 'Description', '', false);
Please add empty line in the end of SQL scripts

2024-02-16 09:23 UTC, olekskov commented on src/test/java/com/example/books/controller/ShoppingCartControllerTest.java
> +    }, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
Please check if it's possible to move majority of scripts to class level to make methods annotations shorter

2024-02-16 11:47 UTC, DZarudnyi commented
Thank you, that review was very helpful! I actually learned a lot

2024-02-16 16:13 UTC, okuzan approved these changes

2024-02-16 16:13 UTC, okuzan commented on docker-compose.yml
> +      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
remove comment, add empty line at EOF

2024-02-16 16:13 UTC, okuzan commented on src/test/java/com/example/books/controller/ShoppingCartControllerTest.java
> +        mockMvc.perform(delete("/api/cart/cart-items/1"))
use your constant

2024-02-16 17:11 UTC, merged