Added search request
DZarudnyi/SpringBootBookShop pull request #3
Opened 2023-12-19 20:53 UTC by DZarudnyi

2023-12-19 20:55 UTC, DZarudnyi commented
So i was wondering how could i add search by part of the field, not exact match?

2023-12-20 12:42 UTC, okuzan requested changes

2023-12-20 12:42 UTC, okuzan commented on src/main/java/com/example/books/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException(
let's throw NoSuchElement

2023-12-20 12:42 UTC, okuzan commented on src/main/java/com/example/books/repository/book/BookSpecificationBuilder.java
> +                    .getSpecification(searchParameters.authors()));
extract literals to constants

2023-12-20 12:42 UTC, okuzan commented on src/main/java/com/example/books/repository/book/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
p is a bad naming

2023-12-20 18:31 UTC, Ivan95kos approved these changes
Nice

2023-12-22 19:43 UTC, merged